# name: Sync to Hugging Face hub
# on:
#   push:
#     branches: [main]

#   # to run this workflow manually from the Actions tab
#   workflow_dispatch:

# jobs:
#   sync-to-hub:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           fetch-depth: 0
#       - name: Push to hub
#         env:
#           HF_TOKEN: ${{ secrets.HF_TOKEN }}
#         run: git push https://hans141:$HF_TOKEN@huggingface.co/spaces/Hans141/demo-test/
name: 'Issue opened'
on:
  issues:
    types:
      - opened
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: nopr
          column: Todo
          repo-token: ${{ secrets.GH_PAT }}